# A generic, single-database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration file names; here we use
# oliver's preferred format
# file_template = %%(rev)s_%%(slug)s

# timezone to use when rendering the date within the migration file
# leave blank for local time
# timezone =

# max length of characters to use for "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment during the 'revision' command,
# regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc files to be created [at the risk of
# python 3.4/3.5/3.6/3.7/3.8/3.9/3.10/3.11/etc. becoming slightly confused]
# sourceless = false

# version location specification; This defaults
# to alembic/versions.  When using multiple version
# directories, initial revisions must be specified with --version-path
# version_locations = %(here)s/alembic/versions

# the terminal width used for reporting; if not set, the terminal width
# will be queried at runtime.
# output_width = 80

# logging configuration section
sqlalchemy.url = postgresql+asyncpg://vehitrack_user:password@localhost/vehitrack

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
